name: ${project.artifactId}
version: ${project.version}
main: net.okocraft.respawner.Respawner
author: LazyGon
api-version: 1.14
description: Plugin that implements respawn command.

commands:
  respawn:
    description: "Command that respawns dead player."
    permission: "respawner.use"

permissions:
  respawner.use:
    default: op