name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
authors:
  - LazyGon
  - Kamesuta
api-version: 1.15
description: Plugin that implements respawn command.

commands:
  respawn:
    description: "Command that respawns dead player."
    permission: "respawner.use"

permissions:
  respawner.use:
    default: op